# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e73114de15f4e82322140fb9c959971806fa3aa93fec657a3d5b532521e55172bd38ffa264175ec42f327897b028b0cf2d842696ab8fd34aa0469bfdb4d3265

test:
  secret_key_base: 027c78c03deb2bf0e593e4f7fbfdcf0c1e03182ea215651b55d86e124c95ed1f880fb3ec6868c034ed7d050f191b8b657b0b54a5811f3de4d2481035d4b632cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
